### ISSUE TITLE
Created image has invalid date

### ISSUE THREAD

**Issue by jacob-carlborg** [oracle/smith#3]
I created an image using `smith`. I uploaded it to a local docker registry using the `-d` flag to convert it to a Docker image. I then pulled down the image locally and it works perfectly fine. Running `docker images` shows that the image was created 292 years ago. I also pushed the image to my private GitLab instance, which contains a built-in Docker registry. Viewing the registry in GitLab resulted in a 500 page and an exception was thrown due to an invalid date.

One can argue that GitLab should be able to handle this since it works fine in Docker, both locally and in my local registry. But I think it would be really nice if `smith` could set the date correctly, if possible.

I've already reported an issue to GitLab: https://gitlab.com/gitlab-org/gitlab-ce/issues/34988.

**Comment by vishvananda** [comment]
Hi Jacob,
Smith purposefully omits the date so that builds are completely reproducible and the oci config has the same sha (see discussion https://github.com/opencontainers/image-spec/issues/399). Ideally the date would be an annotation elsewhere (perhaps in the the image-manifest) to avoid arbitrarily changing the sha. Unfortunately this means that docker doesn't display a friendly created date. I suppose we could set the date when uploading to the registry to be a bit more user friendly.

**Comment by jacob-carlborg** [comment]
> Smith purposefully omits the date so that builds are completely reproducible and the oci config has the same

I see.

> I suppose we could set the date when uploading to the registry to be a bit more user friendly

That would be nice.

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
I verified now that this is working, thanks.
